let sun = document.getElementById('sun');
let mercury = document.getElementById('mercury');
let mercuryInfo = document.getElementById('mercuryInfo');
let venus = document.getElementById('venus');
let venusInfo = document.getElementById('venusInfo');
let earth = document.getElementById('earth');
let earthInfo = document.getElementById('earthInfo');
let mars = document.getElementById('mars');
let marsInfo = document.getElementById('marsInfo');
let jupiter = document.getElementById('jupiter');
let jupiterInfo = document.getElementById('jupiterInfo');
let saturn = document.getElementById('saturn');
let saturnInfo = document.getElementById('saturnInfo');
let uranus = document.getElementById('uranus');
let uranusInfo = document.getElementById('uranusInfo');
let neptune = document.getElementById('neptune');
let neptuneInfo = document.getElementById('neptuneInfo');
let pluto = document.getElementById('pluto');
let plutoInfo = document.getElementById('plutoInfo');
let objects = new tracking.ObjectTracker('face');

objects.on('track', function(event) {
  if (event.data.length === 0) {
    // No objects were detected in this frame.
  } else {
    event.data.forEach(function(rect) {
      // console.log(rect.x, rect.y, rect.height, rect.width)
      console.log(rect.height);
      if (rect.height >= 120){
        // mercury
        sun.style.top = "1850px";
        sun.style.width = "1500px";
        sun.style.left = "50px";
        mercury.style.width = "400px";
        mercury.style.top = "1450px";
        mercury.style.left = "230px";
        mercuryInfo.style.visibility = "visible";
        venus.style.top = "3000px";
        venusInfo.style.visibility = "hidden";
        earth.style.top = "3000px";
        earthInfo.style.visibility = "hidden";
        mars.style.top = "3000px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.top = "3000px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.top = "3000px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 100 && rect.height < 120){
        // venus
        sun.style.top = "1900px";
        sun.style.width = "1400px";
        sun.style.left = "100px";
        mercury.style.width = "300px";
        mercury.style.top = "1570px";
        mercury.style.left = "300px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "400px";
        venus.style.top = "1020px";
        venus.style.left = "680px";
        venusInfo.style.visibility = "visible";
        earth.style.top = "3000px";
        earthInfo.style.visibility = "hidden";
        mars.style.top = "3000px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.top = "3000px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.top = "3000px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";

      }
      else if (rect.height >= 80 && rect.height < 100){
        // earth
        sun.style.top = "1950px";
        sun.style.width = "1300px";
        sun.style.left = "150px";
        mercury.style.width = "200px";
        mercury.style.top = "1735px";
        mercury.style.left = "350px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "300px";
        venus.style.top = "1230px";
        venus.style.left = "510px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "400px";
        earth.style.top = "700px";
        earth.style.left = "780px";
        earthInfo.style.visibility = "visible";
        mars.style.top = "3000px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.top = "3000px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.top = "3000px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 70 && rect.height < 80){
        // mars
        sun.style.top = "2000px";
        sun.style.width = "1200px";
        sun.style.left = "200px";
        mercury.style.width = "100px";
        mercury.style.top = "1815px";
        mercury.style.left = "375px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "200px";
        venus.style.top = "1390px";
        venus.style.left = "475px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "300px";
        earth.style.top = "950px";
        earth.style.left = "325px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "400px";
        mars.style.top = "465px";
        mars.style.left = "325px";
        marsInfo.style.visibility = "visible";
        jupiter.style.top = "3000px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.top = "3000px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 60 && rect.height < 70){
        // jupiter
        sun.style.top = "2000px";
        sun.style.width = "1100px";
        sun.style.left = "250px";
        mercury.style.width = "50px";
        mercury.style.top = "1820px";
        mercury.style.left = "600px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "100px";
        venus.style.top = "1585px";
        venus.style.left = "650px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "200px";
        earth.style.top = "1285px";
        earth.style.left = "375px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "300px";
        mars.style.top = "800px";
        mars.style.left = "525px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "400px";
        jupiter.style.top = "230px";
        jupiter.style.left = "250px";
        jupiterInfo.style.visibility = "visible";
        saturn.style.top = "3000px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 50 && rect.height < 60){
        // saturn
        sun.style.top = "2100px";
        sun.style.width = "1000px";
        sun.style.left = "300px";
        mercury.style.width = "40px";
        mercury.style.top = "1905px";
        mercury.style.left = "600px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "50px";
        venus.style.top = "1705px";
        venus.style.left = "645px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "100px";
        earth.style.top = "1505px";
        earth.style.left = "445px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "200px";
        mars.style.top = "1150px";
        mars.style.left = "600px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "300px";
        jupiter.style.top = "765px";
        jupiter.style.left = "825px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "400px";
        saturn.style.top = "310px";
        saturn.style.left = "400px";
        saturnInfo.style.visibility = "visible";
        uranus.style.top = "3000px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 40 && rect.height < 50){
        // uranus
        sun.style.top = "2150px";
        sun.style.width = "900px";
        sun.style.left = "350px";
        mercury.style.width = "30px";
        mercury.style.top = "2020px";
        mercury.style.left = "503px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "40px";
        venus.style.top = "1827px";
        venus.style.left = "541px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "50px";
        earth.style.top = "1582px";
        earth.style.left = "597px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "100px";
        mars.style.top = "1279px";
        mars.style.left = "654px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "200px";
        jupiter.style.top = "938px";
        jupiter.style.left = "802px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "300px";
        saturn.style.top = "568px";
        saturn.style.left = "352px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "400px";
        uranus.style.top = "23px";
        uranus.style.left = "822px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "3000px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 35 && rect.height < 40){
        // neptune
        sun.style.top = "2200px";
        sun.style.width = "800px";
        sun.style.left = "400px";
        mercury.style.width = "20px";
        mercury.style.top = "2177px";
        mercury.style.left = "562px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "30px";
        venus.style.top = "2005px";
        venus.style.left = "551px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "40px"
        earth.style.top = "1816px";
        earth.style.left = "607px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "50px";
        mars.style.top = "1632px";
        mars.style.left = "504px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "100px";
        jupiter.style.top = "1334px";
        jupiter.style.left = "577px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "200px";
        saturn.style.top = "971px";
        saturn.style.left = "700px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "300px";
        uranus.style.top = "558px";
        uranus.style.left = "918px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "400px";
        neptune.style.top = "20px";
        neptune.style.left = "535px";
        neptuneInfo.style.visibility = "visible";
        pluto.style.top = "3000px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height < 35){
        // pluto
        sun.style.top = "2250px";
        sun.style.width = "700px";
        sun.style.left = "450px";
        mercury.style.width = "10px";
        mercury.style.top = "2220px";
        mercury.style.left = "562px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "20px";
        venus.style.top = "2080px";
        venus.style.left = "587px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "30px";
        earth.style.top = "1913px";
        earth.style.left = "632px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "40px";
        mars.style.top = "1773px";
        mars.style.left = "509px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "50px";
        jupiter.style.top = "1529px";
        jupiter.style.left = "556px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "100px";
        saturn.style.top = "1264px";
        saturn.style.left = "597px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "200px";
        uranus.style.top = "938px";
        uranus.style.left = "356px";
        uranusInfo.style.visibility = "visible";
        neptune.style.width = "300px";
        neptune.style.top = "585px";
        neptune.style.left = "510px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "400px";
        pluto.style.top = "5px";
        pluto.style.left = "868px";
        plutoInfo.style.visibility = "visible";
      }
      else {
        sun.style.top = "800px";
        sun.style.width = "1600px";
        sun.style.left = "0px";
        mercury.style.width = "23px";
        mercury.style.top = "1838px";
        mercury.style.left = "0px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "53px";
        venus.style.top = "1861px";
        venus.style.left = "23px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "60px";
        earth.style.top = "1914px";
        earth.style.left = "76px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "53px";
        mars.style.top = "1974px";
        earth.style.left = "120px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "200px";
        jupiter.style.top = "2027px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "150px";
        saturn.style.top = "2227px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "100px";
        uranus.style.top = "2377px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "100px";
        neptune.style.top = "2477px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "23px";
        pluto.style.top = "2577px";
        plutoInfo.style.visibility = "hidden";
      }
    });
  }
});

tracking.track('#myVideo', objects, {camera: true})
